### ISSUE TITLE
DeformConvPack_d和DeformConvPack_d的区别

### ISSUE THREAD

**Issue by coder-people** [XinyiYing/D3Dnet#16]
这两个函数在实现功能上面有什么区别

**Comment by XinyiYing** [comment]
没理解你的意思，你提出的两个函数名称是一样的

**Comment by coder-people** [comment]
DeformConvPack_d和DeformConvPack
不好意思打错了，DeformConvPack是三个方向都有offset是吗，DeformConvPack_d可以选择维度

**Comment by XinyiYing** [comment]
是的
