### ISSUE TITLE
Question about D3D operation.

### ISSUE THREAD

**Issue by YDDDDG** [XinyiYing/D3Dnet#19]
Hi,
I replace 3Dconv with your 3D-Deformable-Cov in my model. However, the GPU memory cost increases from about 4000M to more than 10,000M. Even I adjusted the batch size from 8 to 1 and the path size from128*128 to 16*16, it still OUT OF MEMORY. 

I wanna know whether the D3D operation does require very much GPU memory or maybe there is something wrong with my model.
Hope for your reply!

**Comment by XinyiYing** [comment]
D3Dnet cascaded 5 residual D3Ds (i.e., a total of 10 D3Ds) with kernel size of 3 and channel length of 64. When we perform 4x SR on Vid4 dataset (average resolution of HR is 700*500, batch size=1, input frames=7), the GPU memory cost is 2.5G. Then we replace D3Ds in D3Dnet by C3Ds, the GPU memory cost is 1.2G. It is worth noting that deformable operation actually increases the GPU memory cost for about 2.08 times.

**Comment by YDDDDG** [comment]
Thanks for your detailed reply!
