### ISSUE TITLE
Is there any quick way to perform inference using the pretrained model on an input video or image file??

### ISSUE THREAD

**Issue by rushirajsherlocked** [XinyiYing/D3Dnet#23]

**Comment by XinyiYing** [comment]
For quick inference:
1. prepare test dataset 
download your datasets and prepare test data in code/data as below:
 data
  └── dataset_1
         └── scene_1
               └── hr    
                  ├── hr_01.png  
                  ├── hr_02.png  
                  ├── ...
                  └── hr_M.png    
               └── lr_x4
                  ├── lr_01.png  
                  ├── lr_02.png  
                  ├── ...
                  └── lr_M.png   
         ├── ...		  
         └── scene_M
  ├── ...    
  └── dataset_N      

2. Compile deformable 3D convolution:
1) Cd to code/dcn.
2) For Windows users, run cmd make.bat. For Linux users, run bash make.sh. The scripts will build D3D automatically and create some folders.
3) See code/dcn/test.py for example usage.

3. perform inference
python --dataset [dataset_1] test.py

**Comment by XinyiYing** [comment]
1. prepare test dataset 
download your datasets and prepare test data in code/data as below:
```
 data
  └── dataset_1
         └── scene_1
               └── hr    
                  ├── hr_01.png  
                  ├── hr_02.png  
                  ├── ...
                  └── hr_M.png    
               └── lr_x4
                  ├── lr_01.png  
                  ├── lr_02.png  
                  ├── ...
                  └── lr_M.png   
         ├── ...		  
         └── scene_M
  ├── ...    
  └── dataset_N      
```

2. Compile deformable 3D convolution:
Cd to code/dcn.
For Windows users, run cmd make.bat. For Linux users, run bash make.sh. The scripts will build D3D automatically and create some folders.
See code/dcn/test.py for example usage.

3. perform inference
python --dataset [dataset_1] test.py

**Comment by rushirajsherlocked** [comment]
Thank you very much for the quick reply! :) However, I just wanted to know that if I have a low-resolution input video/image (basically I cannot create a test dataset with an LR- HR image pair as you explained), is there any way I can perform inference directly on the LR image and get an HR image as output?? I have already compiled deformable 3D convolution and also made a test run for training the network.

Thanks!

**Comment by XinyiYing** [comment]
Thank you for your comment. We have added inference.py and adjust the dataset.py in our code to offer a direct inference on D3Dnet.

**Comment by rushirajsherlocked** [comment]
Thank you very much for providing the inference file! I will check it out soon!
