### ISSUE TITLE
No module named 'DCN'

### ISSUE THREAD

**Issue by Fly-Pluche** [XinyiYing/D3Dnet#26]
I have run make.sh firstly.
Then I run the test.py.
ModuleNotFoundError: No module named 'DCN'.
![image](https://user-images.githubusercontent.com/73021377/127485752-83c82e6c-328e-4e48-9189-e7fd19661a69.png)

I don't know why I don't have DCN.

**Comment by BinLi-git** [comment]
me too ,do you resolve?

**Comment by Fly-Pluche** [comment]
No ,I havn't.I am so annoyed about it.I don't know why it was lost.
┭┮﹏┭┮

**Comment by BinLi-git** [comment]
I think should throught bash make.sh or cmd make.bat to install environment,but I can not run make.sh success

**Comment by Fly-Pluche** [comment]
Oh ，I get it!
Just can have it after I successed run bash make.sh.
Maybe I ran failed before ,but I thought it successful.
What's your wrong when you ran make.sh?
Lack of GPU?

**Comment by BinLi-git** [comment]
> Oh ，I get it!
> Just can have it after I successed run bash make.sh.
> Maybe I ran failed before ,but I thought it successful.
> What's your wrong when you ran make.sh?
> Lack of GPU?
 I can not install g++ on linux

**Comment by Fly-Pluche** [comment]
You can try to install g++ successfully to deal with it

**Comment by Heart-Sniper** [comment]
if you are using Jupyter notebook, remerber to restart kernel after running make.sh. Otherwise it won't import the new package. How foolish I am to check this error for hours.

**Comment by bibinkunjumon** [comment]
cannt i run it without gpu? I am trying to implement DG-Font git repo.
